<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="61716" started-at="2019-05-23T08:44:42Z" finished-at="2019-05-23T08:45:43Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="61716" started-at="2019-05-23T08:44:42Z" finished-at="2019-05-23T08:45:43Z">
      <class name="ze.page2test">
        <test-method status="PASS" signature="setup()[pri:0, instance:ze.page2test@604ed9f0]" name="setup" is-config="true" duration-ms="5865" started-at="2019-05-23T08:45:26Z" finished-at="2019-05-23T08:45:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="main()[pri:0, instance:ze.page2test@604ed9f0]" name="main" duration-ms="10810" started-at="2019-05-23T08:45:31Z" finished-at="2019-05-23T08:45:42Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Google2] but found [Google]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Google2] but found [Google]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at ze.page2test.main(page2test.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- main -->
      </class> <!-- ze.page2test -->
      <class name="ze.page1test">
        <test-method status="PASS" signature="setup()[pri:0, instance:ze.page1test@91161c7]" name="setup" is-config="true" duration-ms="38739" started-at="2019-05-23T08:44:42Z" finished-at="2019-05-23T08:45:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="main()[pri:0, instance:ze.page1test@91161c7]" name="main" duration-ms="4977" started-at="2019-05-23T08:45:21Z" finished-at="2019-05-23T08:45:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- main -->
      </class> <!-- ze.page1test -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
